### ISSUE TITLE
Build failing on Linux 20.04

### ISSUE THREAD

**Issue by AndreaRicchi** [guerinoni/qode#1]
Building on Pop!_os 20.04, with Qt 5.12.8 and GCC 9.3.0 fails.

Missing `#include <memory>` in _ToolBar.hpp_ header files.

**Comment by guerinoni** [comment]
I'm using Qt 5.14.2 :D

**Comment by AndreaRicchi** [comment]
Well, since 5.12 is the LTS version I think it is better to make the application buildable out of the box.

**Comment by guerinoni** [comment]
I know but in 19th May the LTS will be 5.15

**Comment by AndreaRicchi** [comment]
Then I suggest defining a minimum version of Qt.

**Comment by guerinoni** [comment]
I will adjust README :)

**Comment by AndreaRicchi** [comment]
I mean in the CMakeList to prevent build if the Qt version is lower than 5.14. Most of the people won't read the README but will just clone the repo and try to build it.

**Comment by guerinoni** [comment]
Yes, cool! I need also pipeline to create package like .exe AppImage and other format... :P
